Repository yaklang/yaklang, pull requests merged in 2023-08, with the labels that each got.

#268 fix(grpc invalid UTF8) replace all invalid UTF8 byte to "■"
  common/yakgrpc/yakit/risk.go
Labels: bug

#318 fix(crawlerx) context canceled caused by localstorage save
  common/crawlerx/starter.go
Labels: ready

#328 use new plugin avator
  common/coreplugin/coreplugin.go
Labels: ready

#329 fix sm2 encrypt
  common/gmsm/sm2/sm2.go
  common/yak/yaklib/codec/sm2.go
  common/yakgrpc/grpc_fuzzer_hotpath_test.go
Labels: ready

#330 feat(split `ssa` package to `ssa4yak` )
  common/yak/ssa/block.go
  common/yak/ssa/builder.go
  common/yak/ssa/buildin_func.go
  common/yak/ssa/const.go
  common/yak/ssa/create.go
  common/yak/ssa/disasm.go
  common/yak/ssa/emit.go
  common/yak/ssa/error.go
  common/yak/ssa/func.go
  common/yak/ssa/instruction.go
  common/yak/ssa/phi.go
  common/yak/ssa/program.go
  common/yak/ssa/ssa.go
  common/yak/ssa/ssa_inspect.go
  common/yak/ssa/ssa_vars.go
  common/yak/ssa/type_inference.go
  common/yak/ssa/use.go
  common/yak/ssa/variable.go
  common/yak/ssa4yak/builder.go
  common/yak/ssa4yak/builder_ast.go
  common/yak/ssa4yak/builder_object.go
  common/yak/ssa4yak/builder_test.go
  common/yak/ssa4yak/buildin_func.go
  common/yak/ssa4yak/range.go
  common/yak/ssa4yak/ssa_inspect_test.go
  common/yak/ssa4yak/ssa_vars_test.go
Labels: enhancement, ready

#333 fix(fuzztag) alias overwrite del {{int}} alias {{p}}
  common/fp/cmd/README.md
  common/fuzztag/node.go
  common/mutate/fuzztag.go
Labels: ready

#337 add(fuzztag) int step generation
  common/mutate/fuzztag.go
  common/mutate/fuzztag_test.go
Labels: ready

#334 fix(fuzzer-matcher) match predefined variables bug
  common/yakgrpc/grpc_fuzzer.go
  common/yakgrpc/grpc_fuzzer_test.go
Labels: ready

#340 fix(debug-plugin): empty input error
  common/yak/hook_mixed_plugin_caller.go
  common/yakgrpc/grpc_http_request_builder.go
  common/yakgrpc/grpc_http_request_builder_scripts.yak
  common/yakgrpc/grpc_http_request_builder_test.go
  common/yakgrpc/grpc_http_request_debug.go
  common/yakgrpc/yakit/yak_script.go
Labels: ready

#349 feat: webfuzzer tab index
  common/yakgrpc/yakgrpc.proto
  common/yakgrpc/yakit/fuzzer_task.go
  common/yakgrpc/ypb/yakgrpc.pb.go
  common/yakgrpc/ypb/yakgrpc_grpc.pb.go
Labels: ready

#324 add(mitm): add custom navigation page
  common/crep/mitm.go
  common/crep/static/css/bootstrap.min.css
  common/crep/static/favicon.ico
  common/crep/static/js/bootstrap.min.js
  common/crep/static/js/jquery-3.6.0.min.js
  common/crep/static/navtab.html
  common/crep/static/yakit-logo.png
Labels: ready

#353 fix(arpx): arp cache
  common/pcapx/arpx/arp.go
  common/pcapx/builder.go
  common/pcapx/builder_test.go
Labels: ready

#356 add(mitm) 添加快捷键提示
  common/crep/static/navtab.html
Labels: ready

#358 报告
  common/cve/cveresources/cwe.go
  common/yakgrpc/yakit/risk_exports.go
Labels: ready

#355 fix(pcapx): make it run on action
  .github/workflows/essential-tests.yml
  common/pcapx/builder.go
  common/pcapx/link.go
Labels: ready

#359 add empty host case
  common/martian/v3/proxy.go
  common/utils/http_dumper.go
  common/utils/http_dumper_test.go
  common/utils/http_request_builder.go
  common/utils/http_request_builder_test.go
  common/utils/lowhttp/httpctx/base.go
  common/utils/lowhttp/utils_test.go
  common/utils/str_utils.go
  common/utils/str_utils_test.go
  common/yak/yakdoc/func_utils.go
  common/yak/yaklib/codec/strconv.go
  common/yak/yaktest/mustpass/mustpass_base_test.go
Labels: ready
