Repository yaklang/yaklang, pull requests merged in 2023-09, with the labels that each got.

#370 Fix/debugger/2023 9 1
  common/yak/antlr4yak/dap/prettyprint.go
  common/yak/antlr4yak/dap/resp.go
  common/yak/antlr4yak/dap/server_test.go
  common/yak/antlr4yak/dap/session.go
  common/yak/antlr4yak/yakvm/debugger.go
  common/yak/antlr4yak/yakvm/vm_exec.go
Labels: ready

#367 fix: InteractiveDebugger bind sourcePath
  common/yak/cmd/yak.go
  common/yak/interactive_debugger/debugger.go
Labels: ready

#368 Feature(chaosmaker/pcapx/suricata): generate tcp handshake packet
  common/chaosmaker/chaos_test.go
  common/chaosmaker/choas_maker.go
  common/chaosmaker/dns.go
  common/chaosmaker/handler.go
  common/chaosmaker/http.go
  common/chaosmaker/icmp.go
  common/chaosmaker/inject_test.go
  common/chaosmaker/tcp.go
  common/chaosmaker/udp.go
  common/pcapx/exports.go
  common/pcapx/tcp.go
  common/pcapx/utils.go
  common/suricata/generate/dns.go
  common/suricata/generate/http.go
  common/suricata/generate/http_combination.go
  common/suricata/generate/icmp.go
  common/suricata/generate/tcp.go
  common/suricata/generate/udp.go
  common/suricata/match/http.go
  common/suricata/rule/addr_test.go
  common/suricata/rule/utils.go
  common/suricata/rule/visitor_addr.go
  common/suricata/rule/visitor_port.go
  common/yakgrpc/grpc_chaosmaker.go
Labels: ready

#364 fix(crawlerx):headers & cookies custom set not working
  common/crawlerx/config.go
  common/crawlerx/starter.go
  common/crawlerx/utils.go
  common/crawlerx/utils_test.go
Labels: ready

#378 fix(payload):去除payload尾部的非空格空白符
  common/yakgrpc/grpc_managePayload.go
Labels: ready

#376 fix/feat(pcapx/chaosmaker): tcp flow, tcp segment
  common/chaosmaker/chaos_test.go
  common/chaosmaker/choas_maker.go
  common/chaosmaker/http.go
  common/pcapx/exports.go
  common/pcapx/tcp.go
Labels: ready

#372 fix(risk) limit risk input size
  common/yak/yaktest/mustpass/files/risk_output_limit.yak
  common/yakgrpc/yakit/exportresource.go
  common/yakgrpc/yakit/risk_exports.go
Labels: ready

#382 fix(mitm): mis usage of truncate in before filter
  common/yakgrpc/grpc_mitm.go
  common/yakgrpc/grpc_mitm_filter_manager.go
  common/yakgrpc/grpc_mitm_filter_test.go
Labels: ready

#381 Rookie/fix/hotpatch error save
  common/fuzztag/exec.go
  common/fuzztag/node.go
  common/mutate/fuzztag_exec.go
  common/yak/yak_to_caller_manager.go
  common/yakgrpc/grpc_fuzzer_hotpath_test.go
Labels: ready

#384 Fix/ast/template string
  common/utils/yakunquote/unquote.go
  common/yak/antlr4yak/YaklangLexer.g4
  common/yak/antlr4yak/YaklangParser.g4
  common/yak/antlr4yak/executor_test.go
  common/yak/antlr4yak/parser/YaklangLexer.interp
  common/yak/antlr4yak/parser/YaklangLexer.tokens
  common/yak/antlr4yak/parser/YaklangParser.interp
  common/yak/antlr4yak/parser/YaklangParser.tokens
  common/yak/antlr4yak/parser/yaklang_lexer.go
  common/yak/antlr4yak/parser/yaklang_parser.go
  common/yak/antlr4yak/parser/yaklangparser_base_visitor.go
  common/yak/antlr4yak/parser/yaklangparser_visitor.go
  common/yak/antlr4yak/yakast/literal.go
Labels: ready

#387 Bugfix/dumper concurrent write header
  common/utils/http_dumper.go
  common/utils/http_dumper_test.go
Labels: ready

#383 impr large httpflow
  common/domainextractor/extractdomain.go
  common/domainextractor/extractdomain_test.go
  common/yakgrpc/grpc_httpflow_test.go
  common/yakgrpc/grpc_mitm.go
  common/yakgrpc/yakit/httpflow.go
Labels: ready

#380 Feat/pcap cmd
  common/pcapx/pcaputil/capture.go
  common/pcapx/pcaputil/capture_test.go
  common/pcapx/pcaputil/open_device.go
  common/pcapx/pcaputil/start.go
  common/pcapx/pcaputil/start_test.go
  common/pcapx/pcaputil/suricata-test.rules
  common/suricata/match/addr.go
  common/suricata/match/dns.go
  common/suricata/match/http.go
  common/suricata/match/icmp.go
  common/utils/routine.go
  common/yak/cmd/yak.go
  common/yak/cmd/yakcmds/pcap.go
Labels: ready

#389 add fileopt to string fuzzer and codec
  common/consts/yakit.go
  common/mutate/fuzztag.go
  common/yakgrpc/grpc_codec.go
  common/yakgrpc/grpc_codec_test.go
  common/yakgrpc/grpc_fuzzer.go
  common/yakgrpc/grpc_fuzzer_string_test.go
Labels: ready

#392 dns + tcp + tls in dialx
  common/netx/config.go
  common/netx/dial.go
  common/netx/dialx.go
  common/netx/dialx_util.go
  common/netx/lookup.go
  common/utils/lowhttp/exec.go
Labels: ready

#393 merge fuzztag params
  common/yakgrpc/grpc_fuzzer.go
  common/yakgrpc/grpc_fuzzer_sequence_test.go
Labels: ready

#388 feat(httpflow): allow get bare request and response
  common/utils/lowhttp/httpctx/base.go
  common/utils/unsafe.go
  common/yakgrpc/grpc_httpflow.go
  common/yakgrpc/grpc_httpflow_test.go
  common/yakgrpc/grpc_mitm.go
  common/yakgrpc/yakgrpc.proto
  common/yakgrpc/yakit/project_kv.go
  common/yakgrpc/ypb/yakgrpc.pb.go
  common/yakgrpc/ypb/yakgrpc_grpc.pb.go
Labels: enhancement, ready

#405 fix vulinbox
  common/vulinbox/vul_cryptojs_base.go
Labels: vulinbox

#403 fix(mitm): url filter
  common/utils/str_utils.go
  common/utils/str_utils_test.go
Labels: ready

#410 feat(QueryFuzzerHistoryTasks): alllow order and orderby
  common/yakgrpc/yakit/fuzzer_task.go
Labels: ready

#411 bugfix: let execfirst associated to runtime id
  common/mutate/http_fuzz.go
  common/mutate/http_fuzz_batch.go
  common/mutate/http_fuzz_handlers.go
  common/mutate/http_pool.go
  common/yakgrpc/grpc_http_request_debug_test.go
Labels: ready

#418 improve plain http proxy without proxy-conn
  common/crep/mitm_hijack_handler.go
  common/minimartian/v3/proxy.go
  common/utils/http_dumper.go
  common/utils/lowhttp/httpctx/base.go
  common/yakgrpc/grpc_mitm_plainproxy_test.go
Labels: ready

#420 add all() params and skip self-contained
  common/yak/httptpl/config.go
  common/yak/httptpl/exports.go
  common/yak/httptpl/exports_test.go
  common/yak/httptpl/nuclei.go
  common/yak/httptpl/nuclei_test.go
  common/yak/httptpl/yaktpl.go
  common/yak/httptpl/yaktpl_exec.go
Labels: ready

#423 fix(mitm): isHTTPS always false when using HTTP Proxy
  common/crep/mitm_hijack_handler.go
Labels: ready

#425 fix(portscan) && add(mock) tcp
  common/fp/webfingerprint/fetcher.go
  common/yak/yaklib/tcp.go
  common/yak/yaktest/mustpass/files/mock_tcp_probe.yak
Labels: ready

#428 renog tls alg
  common/crep/mitm_config.go
  common/gmsm/gmtls/gmcredentials/credentials.go
  common/netx/badcase_test.go
  common/netx/dial.go
  common/netx/dialx.go
  common/utils/utils.go
Labels: ready

#430 fix(script) format yak script
  common/yakgrpc/grpc_simple_detect_script.yak
Labels: ready

#438 便携版：Feature/go0p/fix simple scan brute bug
  common/yakgrpc/grpc_simpleDetect.go
  common/yakgrpc/grpc_simple_detect_script.yak
  common/yakgrpc/progress_manager.go
Labels: ready

#441 fix large json-extractor bad behavior
  common/yakgrpc/yakit/httpflow.go
Labels: ready

#445 fix(new-risk) order created_at to id
  common/yakgrpc/yakit/risk.go
Labels: ready

#446 feature: netx can preset client certs
  common/netx/badcase_test.go
  common/netx/dial.go
  common/netx/dialx.go
  common/netx/mustpass/tlsconfig_auth_test.go
  common/netx/tls.go
  common/netx/tlsinspect.go
  common/utils/tlsutils/pfx_test.go
  common/utils/tlsutils/retrieve_test.go
  common/utils/tlsutils/tls.go
  common/yak/yaklib/tls.go
  common/yak/yaktest/servicescan_test.go
Labels: ready

#451 feature: add support for der format ca
  common/crep/mitm_config.go
  common/yak/yaklib/mitm.go
  common/yak/yaktest/mustpass/files/mitm_selfsigncert.yak
  common/yak/yaktest/mustpass/mustpass_base_test.go
Labels: ready

#452 payload和var互转
  common/yak/httptpl/nuclei.go
  common/yak/httptpl/yaktpl_variables.go
  common/yakgrpc/grpc_fuzzer_yaml.go
Labels: ready

#457 fix(vm formatter): double comment
  common/yak/antlr4yak/executor_test.go
  common/yak/antlr4yak/yakast/formatter.go
Labels: ready

#460 修复插件bug
  common/coreplugin/base-yak-plugin/Fastjson 综合检测.yak
Labels: ready

#468 修复一些字段
  common/yakgrpc/grpc_fuzzer_yaml.go
Labels: ready

#477 fix(httpflow) duplicate ID
  common/yakgrpc/grpc_scanPort_script.yak
  common/yakgrpc/yakit/httpflow.go
Labels: ready

#481 Feature/go0p/fix simple scan misc
  common/yakgrpc/grpc_simple_detect_script.yak
Labels: ready

#483 ci(web-doc): auto publish
  .github/workflows/generate-web-doc.yml
Labels: ready

#488 fix crypto/js vulinbox
  common/vulinbox/vul_cryptojs_base.go
Labels: vulinbox, ready

#492 fix(web-doc): lower fragment
  common/yak/yakdoc/generate_web_doc/generate_web_doc.go
Labels: ready

#490 add mirror http flow to extractor data by code
  common/mutate/http_pool.go
  common/yak/script_engine_for_fuzz.go
  common/yakgrpc/grpc_fuzzer.go
  common/yakgrpc/grpc_fuzzer_hotpath_test.go
Labels: ready

#485 feat(csrf): generate json poc
  common/yak/yaklib/csrf.go
  common/yak/yaklib/csrf_test.go
Labels: ready

#496 fix(ci): try fix grpc MUSTPASS "used of closed network" failure
  common/finscan/create_packets.go
  common/subdomain/subdomain_query_dns_test.go
  common/subdomain/subdomain_zone_transfer_test.go
  common/synscan/create_packets.go
  common/utils/os_utils.go
  common/utils/os_utils_test.go
  common/utils/str_utils.go
  common/vulinbox/model_user.go
Labels: ready

#494 test(chaosmaker): cross verify suricata group matcher
  common/chaosmaker/chaos_test.go
Labels: ready
