Repository yaklang/yaklang, pull requests merged in 2023-12, with the labels that each got.

#731 fix(ssa-rules-cli): param name allow "-_"
  common/yak/plugin_type_analyzer/rules/cli_rules.go
Labels: ready

#738 refactor(mitm-filter):添加mitm-ws filter
  common/utils/host_n_port_utils.go
  common/utils/lowhttp/exec_test.go
  common/utils/lowhttp/utils.go
  common/yakgrpc/grpc_mitm.go
Labels: ready

#740 add (network-diagnose) dhcp name server
  common/utils/system_dns_windows.go
Labels: ready

#788 Modify choice logic
  .github/workflows/manual-build-target.yml
Labels: need review

#793 fix(antlr2util): check token nil
  common/yak/antlr4util/range.go
  common/yak/yak2ssa/range.go
Labels: ready

#782 fix(FixHTTPPacketCRLF):去除为body添加CRLF的逻辑
  common/utils/lowhttp/http_request.go
Labels: ready, need review

#799 refactor(ssa): refactor DisasmLine avoid stack overflow
  common/yak/JS2ssa/builder_test.go
  common/yak/ssa/disasmLine.go
  common/yak/ssa/scope.go
  common/yak/ssa/ssa.go
  common/yak/ssa4analyze/type_inference.go
  common/yak/ssaapi/values.go
  common/yak/yak2ssa/ssa_vars_test.go
Labels: ready

#790 feat(grpc): EvaluatePlugin add code Range
  common/yakgrpc/grpc_smoking_evaluate_plugin.go
  common/yakgrpc/yakgrpc.proto
  common/yakgrpc/ypb/yakgrpc.pb.go
  common/yakgrpc/ypb/yakgrpc_grpc.pb.go
Labels: ready, need frontend

#813 fix(yak_vm):修复并发情况下try catch失效的问题
  common/yak/antlr4yak/yakvm/virtual_machine.go
  common/yak/antlr4yak/yakvm/vm.go
  common/yak/antlr4yak/yakvm/vm_panic.go
Labels: dangerous

#823 fix(debug-plugin-grpc):修复不合理的scanport参数设置
  common/yakgrpc/grpc_http_request_builder_scripts.yak
  common/yakgrpc/grpc_http_request_debug.go
Labels: WIP: work in progress
