Repository yaklang/yaklang, pull requests merged in 2023-07, with the labels that each got.

#48 pcapx basic packet builder
  common/pcapx/builder.go
  common/pcapx/builder_arp.go
  common/pcapx/builder_ethernet.go
  common/pcapx/builder_ip4.go
  common/pcapx/builder_tcp.go
  common/pcapx/builder_test.go
  common/utils/netparser_utils.go
Labels: enhancement

#184 add : 添加漏洞信息，修复 %s bug
  common/coreplugin/base-yak-plugin/基础 XSS 检测.yak
Labels: bug

#206 mitm better msg
  common/martian/v3/proxy.go
  common/martian/v3/proxyutil/proxyutil.go
  common/martian/v3/proxyutil/template.html
  common/utils/lowhttp/httpctx/base.go
  common/yakgrpc/grpc_mitm.go
  common/yakgrpc/yakit/httpflow.go
Labels: enhancement

#196 add more testcase for dns server
  common/facades/dns_servers.go
  common/facades/mockdns_server.go
  common/facades/mockdns_server_test.go
Labels: WIP: work in progress

#236 add leakless config on httpbrute
  common/simulator/config/config.go
  common/simulator/config/data.go
  common/simulator/core/constructor.go
  common/simulator/core/start.go
  common/simulator/export.go
  common/simulator/httpbrute/config.go
  common/simulator/httpbrute/core.go
  common/simulator/httpbrute/main_test.go
Labels: enhancement

#250 fix(vm): panic when assign yak function to function map
  common/yak/antlr4yak/executor_test.go
  common/yak/antlr4yak/yakvm/value.go
  common/yak/antlr4yak/yakvm/value_types.go
Labels: bug, vm

#249 fix/vm/closure_assign check if func.scope == nil?
  common/yak/antlr4yak/executor_test.go
  common/yak/antlr4yak/yakvm/vm_exec.go
Labels: bug, vm
