Repository yaklang/yaklang, pull requests merged in 2023-11, with the labels that each got.

#591 Fix Js2ssa
  common/yak/JS2ssa/builder.go
  common/yak/JS2ssa/builder_ast.go
  common/yak/JS2ssa/builder_test.go
  common/yak/ssa/variable.go
Labels: ready, ssa

#598 fix(web-fuzzer):rematch hitcolor 修复
  common/yakgrpc/grpc_fuzzer.go
Labels: ready

#603 Fixup [ssa4analyze] check key type in getField method
  common/yak/ssa/type.go
  common/yak/ssa4analyze/type_inference.go
  common/yak/yak2ssa/ssa_error_test.go
Labels: ready, ssa

#607 doc(git):
  common/utils/yakgit/checkout.go
  common/utils/yakgit/clone.go
  common/utils/yakgit/commit.go
  common/utils/yakgit/config.go
  common/utils/yakgit/fetch.go
  common/utils/yakgit/githack.go
  common/utils/yakgit/pull.go
Labels: ready

#606 feat(githack): use ConcurrentCopyDirectory
  common/utils/fileutil.go
  common/utils/yakgit/githack.go
Labels: ready

#611 fix(simulator): fix panic of location href jump in js
  common/simulator/httpbrute.go
Labels: ready

#612 doc(math):
  common/yak/yaklib/math.go
Labels: ready

#635 fix(crawlerx): option element not found
  common/crawlerx/action.go
  common/crawlerx/utils.go
Labels: ready

#637 feature use env
  common/yak/cmd/yak.go
Labels: ready, cli

#645 doc(re):
  common/yak/yaklib/regexp.go
  common/yak/yaklib/regexp_extract.go
  common/yak/yaklib/strings.go
Labels: documentation, ready

#661 修复yaml导入导出策略
  common/yakgrpc/grpc_fuzzer_yaml.go
  common/yakgrpc/grpc_fuzzer_yaml_test.go
Labels: ready

#665 fixup(phi_position)fix phi position
  common/yak/ssa/ssa.go
  common/yak/yak2ssa/ssa_vars_test.go
Labels: ready

#672 Doc/context
  common/yak/yaklib/context.go
Labels: ready

#686 Fix/ssa rules cli/get operands
  common/yak/plugin_type_analyzer/rules/cli_rules.go
  common/yak/ssaapi/values.go
Labels: ready

#691 Fix[grpc evaluate]: score start at 100
  common/yakgrpc/grpc_smoking_evaluate_plugin.go
  common/yakgrpc/grpc_smoking_evaluate_plugin_test.go
Labels: bug, ready

#693 fixup(ssa_type) nil assign to types
  common/yak/ssa/type.go
  common/yak/yak2ssa/ssa_error_test.go
Labels: ready

#715 add regen:one
  common/mutate/fuzztag.go
Labels: ready
