Repository yaklang/yaklang, pull requests merged in 2024-02, with the labels that each got.

#943 fix(grpc): get cli code just return code generated from database
  common/yakgrpc/grpc_yaklang_inspect_information.go
  common/yakgrpc/grpc_yaklang_inspect_information_test.go
Labels: ready

#955 feat&fix: fuzzer mutate request params keep raw
  common/utils/lowhttp/modifier.go
  common/utils/lowhttp/modifier_test.go
  common/utils/lowhttp/poc/poc.go
  common/utils/lowhttp/query.go
  common/yakgrpc/grpc_fuzzer.go
  go.work.sum
Labels: ready

#973 fix problem of query with limit before pagination
  common/yakgrpc/yakit/httpflow.go
Labels: ready

#983 [BUGFIX] fix jsonextractor high cpu holding
  common/yakgrpc/yakit/httpflow.go
Labels: ready

#985 [Fix] static_analyze: plugin function rule should filter function
  common/yak/static_analyzer/rules/plugin_function.go
  common/yak/static_analyzer/test/rules_plugin_function_test.go
Labels: StaticAnalysis

#953 adjust space engine interface && fix query port table bug
  common/consts/thirdparty.go
  common/utils/spacengine/fofa.go
  common/utils/spacengine/fofa/fofa.go
  common/utils/spacengine/hunter.go
  common/utils/spacengine/quake.go
  common/utils/spacengine/shodan.go
  common/utils/spacengine/zoomeye.go
  common/yakgrpc/grpc_assets.go
  common/yakgrpc/grpc_config_global_network.go
  common/yakgrpc/grpc_space_engine.go
  common/yakgrpc/grpc_space_engine.yak
  common/yakgrpc/grpc_space_engine_test.go
  common/yakgrpc/yakgrpc.proto
  common/yakgrpc/yakit/port.go
  common/yakgrpc/ypb/yakgrpc.pb.go
  common/yakgrpc/ypb/yakgrpc_grpc.pb.go
Labels: ready

#997 fix webfuzzer response detail is blank
  common/yakgrpc/yakit/httpflow.go
Labels: ready

#1008 temporarily fix bug that brute rdp uncaught error
  common/utils/bruteutils/bruteutils.go
  common/utils/bruteutils/grdp/emission/emitter.go
  common/utils/bruteutils/grdp/protocol/sec/sec.go
  common/utils/bruteutils/rdp.go
Labels: ready

#1010 [Fix] grpc yaklangInspect CliParameter sorted
  common/yak/static_analyzer/information/cli_parameter.go
  common/yakgrpc/grpc_yaklang_inspect_information.go
  common/yakgrpc/grpc_yaklang_inspect_information_test.go
Labels: StaticAnalysis

#1016 feat(crawlerx): add url check config
  common/crawlerx/config.go
  common/crawlerx/exports.go
  common/crawlerx/main.go
Labels: ready

#1015 feat(lib-fuzz): fuzz xml
  common/mutate/http_fuzz.go
  common/mutate/http_fuzz_batch.go
  common/mutate/http_fuzz_handlers.go
  common/mutate/http_fuzz_param.go
  common/mutate/http_fuzz_test.go
  common/mutate/http_fuzz_utils.go
  common/utils/validator.go
  common/yakgrpc/yakit/httpflow.go
Labels: ready, Bravo！
