Repository yaklang/yaklang, pull requests merged in 2024-11, with the labels that each got.

#2055 pluginCorrelation
  common/yak/yaklib/yakit_online.go
  common/yakgrpc/grpc_manageScript_test.go
  common/yakgrpc/yakgrpc.proto
  common/yakgrpc/yakit/yak_script.go
  common/yakgrpc/ypb/yakgrpc.pb.go
  common/yakgrpc/ypb/yakgrpc_grpc.pb.go
Labels: ready

#2060 fix(syntaxflow):all statement should wrap in statement opcode
  common/syntaxflow/sfvm/frame.go
  common/syntaxflow/sfvm/visitor.go
  common/yak/ssaapi/sf_value.go
  common/yak/ssaapi/sf_values.go
Labels: ready

#2071 fix(ssaurl):add nil check in NewValueFromAuditNode
  common/yak/ssaapi/sf_result_value.go
  common/yak/yakurl/ssaurl.go
Labels: ready

#2069 feat(proto):add httpflow message FromPlugin field
  common/yakgrpc/model/httpflow.go
  common/yakgrpc/yakgrpc.proto
  common/yakgrpc/ypb/yakgrpc.pb.go
  common/yakgrpc/ypb/yakgrpc_grpc.pb.go
Labels: ready

#2076 fix(sf_buildin):fix some rule error
  common/syntaxflow/sfbuildin/buildin/java/cwe-89-sql-injection/java-add-string-and-execute-query.sf
  common/syntaxflow/sfbuildin/buildin/java/lib/java-file-write-filename-params.sf
  common/syntaxflow/sfbuildin/buildin/php/cwe-73-unfiltered-file-or-path/php-custom-file-operator.sf
Labels: ready

#2077 feat(lowhttp): LowhttpResponse utils method
  common/utils/lowhttp/config.go
Labels: ready

#2080 feat(grpc):language suggestion support syntaxflow
  common/yakgrpc/grpc_language_suggestion.go
  common/yakgrpc/grpc_language_suggestion_syntaxflow.go
  common/yakgrpc/grpc_language_suggestion_test.go
  common/yakgrpc/yakgrpc.proto
  common/yakgrpc/ypb/yakgrpc.pb.go
  common/yakgrpc/ypb/yakgrpc_grpc.pb.go
Labels: ready

#2090 feat(utils): new curl to http request
  common/utils/lowhttp/curl.go
  common/utils/lowhttp/new_curl.go
  common/utils/lowhttp/new_curl_test.go
  common/utils/lowhttp/poc/poc.go
  common/utils/lowhttp/query.go
  common/utils/str_utils.go
  common/utils/str_utils_test.go
  common/yak/yaklib/codec/codegrpc/codec_grpc_methods.go
  common/yakgrpc/grpc_codec.go
Labels: ready

#2091 feat(utils4analysis):add alert_exact and alert_max for checkResult
  common/yak/ssaapi/test/ssatest/utils4analysis.go
Labels: ready

#2103 fix(coreplugin):when dev mode skip hash check
  common/coreplugin/coreplugin.go
Labels: ready

#2115 feature(httpflow):feature getbody by id or runtimeid
  common/yakgrpc/grpc_httpflow.go
  common/yakgrpc/grpc_httpflow_test.go
  common/yakgrpc/yakgrpc.proto
  common/yakgrpc/yakit/httpflow.go
  common/yakgrpc/ypb/yakgrpc.pb.go
Labels: ready

#2116 feat(lib_poc): Get full query and post params
  common/utils/lowhttp/modifier.go
  common/utils/lowhttp/modifier_test.go
  common/utils/lowhttp/poc/poc.go
  common/yak/yakdoc/doc/doc.gob.gzip
Labels: ready

#2114 feat(fuzzer_seq):
  common/utils/str_utils.go
  common/yak/httptpl/nuclei_utils.go
  common/yak/httptpl/yaktpl_extractor.go
  common/yakgrpc/grpc_fuzzer_sequence_test.go
Labels: ready

#2121 [feature] add peephole filesystem for acc compiling and searching
  common/utils/filesys/fs.go
  common/utils/filesys/peephole.go
  common/utils/filesys/peephole_test.go
  common/utils/filesys/treeview.go
  common/utils/filesys/treeview/viewer.go
Labels: ready

#2125 feature(getbody-risk):export risk body or request
  common/yakgrpc/grpc_httpflow.go
  common/yakgrpc/grpc_httpflow_test.go
  common/yakgrpc/yakgrpc.proto
  common/yakgrpc/ypb/yakgrpc.pb.go
Labels: ready

#2128 fix(go2ssa): fix import value for ExternLib type
  common/yak/go2ssa/builder_ast.go
Labels: ready

#2137 fix(core-plugin):check database path for `SSA 项目编译.yak`
  common/coreplugin/base-yak-plugin/SSA 项目编译.yak
Labels: ready

#2139 feat(static-analysis):add warn for new-risk in main function
  common/yak/static_analyzer/rules/risk_rules.go
  common/yak/static_analyzer/test/rules_risk_test.go
Labels: ready

#2124 refactor(grpc_query_httpflows):
  common/yakgrpc/yakit/httpflow.go
  common/yakgrpc/yakit/httpflow_test.go
Labels: ready

#2146 fix(grpc):check point suffix
  common/yakgrpc/grpc_language_suggestion.go
  common/yakgrpc/grpc_language_suggestion_test.go
  common/yakgrpc/language_server.go
Labels: ready

#2144 fix(crawlerx): add chrome disable-features HttpsUpgrades
  common/crawlerx/starter.go
  common/simulator/browser.go
Labels: ready

#2140 feat(lib-global): add "callable" function
  common/yak/dynamic_eval.go
  common/yak/yaklang/var.go
  common/yak/yaklib/base_funcs.go
  common/yak/yaklib/global.go
Labels: ready

#2109 fix(vm): weak type auto convert, add test
  common/yak/antlr4yak/buildin_operators.go
  common/yak/antlr4yak/executor_test.go
Labels: vm, dangerous

#2170 feat(ssaurl):return pure source code and start line
  common/yak/yakurl/ssaurl.go
Labels: ready

#2167 fix(sfvm): fix debug log
  common/syntaxflow/sfvm/frame.go
  common/syntaxflow/sfvm/vm.go
Labels: ready

#2172 fix http_pool batch target
  common/mutate/http_pool.go
  common/mutate/http_pool_test.go
  common/utils/lowhttp/url_to_request.go
  common/utils/lowhttp/url_to_request_test.go
Labels: ready

#2174 fix http flow color filter
  common/yakgrpc/yakit/httpflow.go
  common/yakgrpc/yakit/httpflow_test.go
Labels: ready

#2175 fix(utils_curl): websocket schema
  common/utils/lowhttp/new_curl.go
  common/utils/lowhttp/new_curl_test.go
Labels: ready

#2183 onlinePluginEnvKey
  common/yak/yaklib/yakit_online.go
Labels: ready

#2182 update pkcs12 dependence to fix the bug of not supporting sha256 algorithm
  common/utils/tlsutils/go-pkcs12/bmp-string.go
  common/utils/tlsutils/go-pkcs12/crypto.go
  common/utils/tlsutils/go-pkcs12/mac.go
  common/utils/tlsutils/go-pkcs12/pbkdf.go
  common/utils/tlsutils/go-pkcs12/pkcs12.go
  common/utils/tlsutils/go-pkcs12/rc2/rc2.go
  common/utils/tlsutils/go-pkcs12/safebags.go
Labels: ready

#2187 fix(syntaxflow):predecessor more exact
  common/syntaxflow/sfvm/frame.go
  common/yak/ssaapi/sf_native_call.go
  common/yak/ssaapi/sf_native_call_code.go
  common/yak/ssaapi/sf_native_call_name.go
  common/yak/ssaapi/sf_value.go
Labels: ready

#2190 fix ci bug
  .github/workflows/exp-cross-build.yml
Labels: ready

#2136 [AI-Improvement] try ai impr stable reader
  common/utils/bytes_reader.go
Labels: AI-Modified

#2188 refactor(codec) AutoDecode and test
  common/yak/yaklib/codec/auto.go
  common/yak/yaklib/codec/auto_test.go
Labels: ready

#2193 fix(go2ssa): fix function range and add test
  common/yak/go2ssa/builder_ast.go
  common/yak/ssaapi/test/golang/golang_range_test.go
Labels: ready

#2196 fix(go2ssa): fix global value and remove todo
  common/yak/go2ssa/builder_ast.go
  common/yak/go2ssa/test/func_scope_test.go
  common/yak/ssa/builder.go
Labels: ready

#2210 add bmp VerboseName && fix fuzztag generater bug
  common/mutate/fuzztag.go
  common/yakgrpc/grpc_fuzztag.go
  common/yakgrpc/grpc_fuzztag_test.go
Labels: ready
