Repository yaklang/yaklang, pull requests merged in 2024-03, with the labels that each got.

#1025 add testcase for sideeffect
  common/yak/ssaapi/exclusive_mask_test.go
  common/yak/ssaapi/exclusive_side_effect_test.go
  common/yak/ssaapi/exclusive_z_top_defs.go
Labels: ready, StaticAnalysis

#1031 fix(yak2ssa): var declaration means force assign
  common/yak/yak2ssa/builder_ast.go
  common/yak/yak2ssa/test/cfg_scope_test.go
Labels: ready

#1030 [SSA-API]: cases for negative-call-stack (preset) and side-effect verification for 'buttom-use'
  common/yak/ssaapi/exclusive_negative_callstack_test.go
  common/yak/ssaapi/exclusive_side_effect_test.go
  common/yak/ssaapi/exclusive_z_bottom_use.go
  common/yak/ssaapi/values.go
Labels: ready

#1040 fix(suggestion): alias type
  common/yak/document.go
  common/yak/yakdoc/doc/doc.gob.gzip
  common/yakgrpc/grpc_language_suggestion.go
  common/yakgrpc/grpc_language_suggestion_test.go
Labels: 🚧：WIP

#1060 fix replacer ext header && add more test
  common/utils/str_utils.go
  common/yakgrpc/grpc_mitm_replacers.go
  common/yakgrpc/grpc_mitm_replacers_test.go
Labels: ready

#1069 feat(httpflow): color tag not taking effect
  common/yakgrpc/grpc_httpflow.go
  common/yakgrpc/grpc_httpflow_test.go
Labels: ready

#1091 fix(crawlerx): update yak cmd
  common/crawlerx/config.go
  common/crawlerx/data.go
  common/crawlerx/starter.go
  common/yak/cmd/yakcmds/crawlerx.go
  common/yak/cmd/yakcmds/scan.go
Labels: ready

#1120 [fix] vm closure function pushWithCopy
  common/yak/antlr4yak/executor_test.go
  common/yak/antlr4yak/yakast/function_decl.go
  common/yak/antlr4yak/yakast/generate_vmcode.go
  common/yak/antlr4yak/yakast/instance_code.go
  common/yak/antlr4yak/yakast/misc.go
  common/yak/antlr4yak/yakast/try.go
  common/yak/antlr4yak/yakast/visitor.go
  common/yak/antlr4yak/yakvm/func.go
  common/yak/antlr4yak/yakvm/vm_exec.go
Labels: vm, ready, Bravo！, 🤗乐

#1132 [Reducer Compile Util] use filesystem loader for compiling a non-entry library or complex project
  common/yak/ssaapi/ssareducer/config.go
  common/yak/ssaapi/ssareducer/reducer.go
  common/yak/ssaapi/ssareducer/reducer_test.go
  common/yak/ssaapi/ssareducer/testlib/aa/a3.yak
  common/yak/ssaapi/ssareducer/testlib/aa/bb/b1.yak
  common/yak/ssaapi/ssareducer/testlib/aa/bb/b1.yak2
  common/yak/ssaapi/ssareducer/testlib/dd/a1.yak
  common/yak/ssaapi/ssareducer/testlib/dd/a2.yak
Labels: compile

#1134 Feature/php2ssa/include
  common/yak/php/PHPLexer.g4
  common/yak/php/PHPParser.g4
  common/yak/php/parser/PHPLexer.interp
  common/yak/php/parser/PHPLexer.tokens
  common/yak/php/parser/PHPParser.interp
  common/yak/php/parser/PHPParser.tokens
  common/yak/php/parser/php_lexer.go
  common/yak/php/parser/php_parser.go
  common/yak/php/parser/phpparser_base_visitor.go
  common/yak/php/parser/phpparser_visitor.go
  common/yak/php/php2ssa/builder.go
  common/yak/php/php2ssa/visit_expr.go
  common/yak/php/tests/builder_expression_test.go
  common/yak/php/tests/func_test.go
Labels: ready, ssa, compile

#1137 fix(crawlerx): fix subdomain scan range not work in some cases
  common/crawlerx/check.go
  common/crawlerx/check_test.go
Labels: ready

#1146 [Feature] brute use tree struction for frontend
  common/utils/bruteutils/auth_func.go
  common/yakgrpc/grpc_brute.go
  common/yakgrpc/grpc_brute_test.go
  common/yakgrpc/yakgrpc.proto
  common/yakgrpc/ypb/yakgrpc.pb.go
Labels: ready

#1150 [Fix] grpc :get bruteType with sort
  common/yakgrpc/grpc_brute.go
  common/yakgrpc/grpc_brute_test.go
Labels: ready

#1119 Feature/go0p/add targeted vuln temporary group
  common/utils/bizhelper/dbutil.go
  common/yakgrpc/grpc_manageScript.go
  common/yakgrpc/grpc_plugin_group.go
  common/yakgrpc/yakgrpc.proto
  common/yakgrpc/yakit/plugin_group.go
  common/yakgrpc/yakit/yak_script_result.go
  common/yakgrpc/ypb/yakgrpc.pb.go
  common/yakgrpc/ypb/yakgrpc_grpc.pb.go
Labels: ready

#1153 ci: fix working
  .github/workflows/wip.yml
Labels: Bravo！

#1154 fix(simulator): fix bugs on target element search
  common/simulator/filter.go
  common/simulator/httpbrute.go
  common/simulator/matrix.go
Labels: ready
