Repository yaklang/yaklang, pull requests merged in 2024-04, with the labels that each got.

#1168 fix(yak-cli): refine parameters
  common/yak/cmd/yakcmds/scan_pluginscan.go
Labels: ready

#1169 Fix/php2ssa/closure class
  common/yak/php/PHPParser.g4
  common/yak/php/parser/PHPParser.interp
  common/yak/php/parser/php_parser.go
  common/yak/php/php2ssa/visit_cls.go
  common/yak/php/tests/func_test.go
  common/yak/php/tests/oop_test.go
Labels: ready

#1184 [Fix] avoid panic when extern function member call
  common/yak/ssa/InstructionEmit.go
  common/yak/ssaapi/ssatest/utils.go
  common/yak/yak2ssa/test/real_yak_test.go
Labels: ready, ssa

#1192 add utils methods for params and first value type
  common/coreplugin/base-yak-plugin/SQL注入-MySQL-ErrorBased.yak
  common/coreplugin/base-yak-plugin/文件包含.yak
  common/mutate/http_fuzz_param.go
  common/mutate/http_fuzz_test.go
  common/utils/host_n_port_utils.go
Labels: ready

#1199 fix(cache):fix ttl cache deadlock
  common/utils/cache.go
Labels: 急

#1205 fix(js):fix js module map read and write
  common/yak/yaklib/js.go
Labels: ready

#1214 fix yso class constant pool load utf8 string error
  common/javaclassparser/java_buffer_writer.go
  common/yakgrpc/grpc_yso.go
  common/yserx/parser.go
Labels: ready

#1218 fix(mitm-cert): log level
  common/crep/mitm.go
Labels: ready

#1232 refactor(redis): remove third-party redis dep
  common/utils/bruteutils/bruteutils.go
  common/utils/bruteutils/redis.go
  common/utils/redis/redis.go
  common/yak/yaklib/redis.go
  go.mod
  go.sum
  go.work.sum
Labels: need review

#1242 support fuzztag text reader && support sleep tag
  common/fuzztagx/fuzztag.go
  common/fuzztagx/parser/generator.go
  common/fuzztagx/reader.go
  common/fuzztagx/reader_test.go
  common/utils/writer.go
Labels: ready

#1257 add cross-build in macos for linux
  .github/workflows/exp-cross-build.yml
  .github/workflows/manual-build-target-ee.yaml
  .github/workflows/manual-build-target.yml
  .github/workflows/manual-build.yml
  .github/workflows/publish-production-version.yml
  .github/workflows/release.yml
  .github/workflows/reuse-build.yml
  common/consts/yakit.go
  common/cybertunnel/icmp_trigger.go
  common/cybertunnel/random_port_trigger.go
  common/finscan/app.go
  common/pcapx/arpx/arp_with_pcap.go
  common/pcapx/arpx/pri.go
  common/pcapx/injector.go
  common/pcapx/pcaputil/capture.go
  common/pcapx/pcaputil/capture_daemon.go
  common/pcapx/pcaputil/config.go
  common/pcapx/pcaputil/open_device.go
  common/synscan/app.go
  common/utils/netutil/cmd/route.go
  common/utils/pcapfix/is_privileged.go
  common/utils/time.go
  common/utils/utils.go
  common/yak/cmd/yakcmds/pcap.go
  common/yak/cmd/yakcmds/utils.go
  common/yakgrpc/grpc_pcapx.go
  go.mod
  go.sum
  go.work.sum
Labels: dangerous

#1256 add case for non-params-get-http-request for upload convertor
  common/utils/lowhttp/modifier.go
  common/yakgrpc/grpc_fuzzer.go
  common/yakgrpc/grpc_fuzzer_test.go
Labels: ready
