Repository yaklang/yaklang, pull requests merged in 2024-07, with the labels that each got.

#1493 feat(webfuzzer): add extra fuzztag "request"
  common/yakgrpc/grpc_fuzzer.go
Labels: ready

#1501 fix(syntaxFlow):functionCallFilter can continue
  common/syntaxflow/sfvm/visitor_filter_expr.go
  common/yak/ssaapi/sf_query.go
  common/yak/ssaapi/test/syntaxflow/call_argument_test.go
Labels: StaticAnalysis

#1499 fix(ssa):create parameterMember by Variable
  common/yak/ssa/call.go
  common/yak/ssa/error_message.go
  common/yak/ssa/value.go
  common/yak/yak2ssa/test/error_test.go
  common/yak/yak2ssa/test/real_yak_test.go
Labels: ready, ssa

#1508 support more operators && support match port
  common/fp/config.go
  common/fp/fingerprint/matcher.go
  common/fp/fingerprint/opcode_test.go
  common/fp/fingerprint/parsers/exp_parser.go
  common/fp/fingerprint/rule/executor.go
  common/fp/fingerprint/rule/model.go
  common/fp/fingerprint_webdetector.go
  common/utils/utils.go
Labels: ready

#1511 feat(syntaxflow):add alert_for statement
  common/syntaxflow/SyntaxFlow.g4
  common/syntaxflow/sf/SyntaxFlow.interp
  common/syntaxflow/sf/SyntaxFlow.tokens
  common/syntaxflow/sf/SyntaxFlowLexer.interp
  common/syntaxflow/sf/SyntaxFlowLexer.tokens
  common/syntaxflow/sf/syntaxflow_lexer.go
  common/syntaxflow/sf/syntaxflow_parser.go
  common/syntaxflow/sfvm/emit.go
  common/syntaxflow/sfvm/frame.go
  common/syntaxflow/sfvm/result.go
  common/syntaxflow/sfvm/visit_statement.go
  common/syntaxflow/sfvm/vm.go
  common/yak/ssaapi/sf_sarif.go
  common/yak/ssaapi/test/syntaxflow/alert_statement_test.go
Labels: ready, StaticAnalysis

#1522 feat(syntaxflow):add env info when the new vm created within old vm
  common/syntaxflow/sfvm/frame.go
  common/syntaxflow/sfvm/value_list.go
  common/syntaxflow/sfvm/value_op.go
  common/syntaxflow/sfvm/vm.go
  common/yak/ssaapi/sf_config.go
  common/yak/ssaapi/sf_prog.go
  common/yak/ssaapi/sf_query.go
  common/yak/ssaapi/sf_value.go
  common/yak/ssaapi/sf_values.go
  common/yak/ssaapi/test/syntaxflow/config_filter_test.go
Labels: ready, StaticAnalysis

#1535 fix(staticAnalyze):check function code empty
  common/yak/static_analyzer/rules/plugin_function.go
  common/yak/static_analyzer/test/rules_plugin_function_test.go
Labels: ready, StaticAnalysis

#1542 fix(cli):handler input language in ssacli
  common/yak/cmd/yakcmds/ssacli.go
  common/yak/ssaapi/ssa_exports.go
Labels: ready

#1538 feat(grpc-filter): project side filter, save to project db first
  common/yakgrpc/grpc_mitm.go
  common/yakgrpc/grpc_mitm_filter.go
  common/yakgrpc/grpc_mitm_filter_manager.go
  common/yakgrpc/grpc_mitm_filter_test.go
  common/yakgrpc/grpc_mitm_websocket_test.go
  common/yakgrpc/yakit/kv.go
Labels: ready

#1547 fix(ssa):fix setDefault nil pointer error
  common/yak/ssa/ssa.go
Labels: bug, ready, ssa

#1549 Fix/home/project create
  common/yakgrpc/grpc_project.go
  common/yakgrpc/grpc_project_test.go
  common/yakgrpc/yakgrpc.proto
  common/yakgrpc/yakit/projects.go
  common/yakgrpc/ypb/yakgrpc.pb.go
  common/yakgrpc/ypb/yakgrpc_grpc.pb.go
Labels: ready

#1584 fix(ssa-rules): allow cli package in mitm plugin
  common/yak/static_analyzer/rules/disable_externlib.go
  common/yak/static_analyzer/test/rules_disable_test.go
Labels: ready

#1597 fix(lsp):analysis unicode fix error
  common/utils/memedit/editor.go
  common/yakgrpc/grpc_language_suggestion_test.go
  common/yakgrpc/language_server.go
Labels: ready

#1600 fix(utils): copyDirectory and add test
  common/utils/fileutil.go
  common/utils/fileutil_test.go
  common/utils/yakgit/githack.go
  common/yak/yaklib/file.go
Labels: ready

#1599 fix GetReverseShellProgramList interface
  common/yakgrpc/grpc_reverseshell_cmd_generator.go
Labels: ready

#1610 feat(yakurl-document): improve fuzzy search
  common/utils/fuzzy/fuzzy.go
  common/yak/yakurl/document.go
Labels: ready
