Repository yaklang/yaklang, pull requests merged in 2024-01, with the labels that each got.

#833 refactor(ssaapi Parse): return Programe and error
  common/coreplugin/static_analyze_test.go
  common/crawler/js.go
  common/yak/JS2ssa/builder.go
  common/yak/JS2ssa/builder_test.go
  common/yak/JS2ssa/test/JsBasic_test.go
  common/yak/JS2ssa/test/ast_test.go
  common/yak/ssaapi/basic_test.go
  common/yak/ssaapi/exclusive_bottom_callstack_test.go
  common/yak/ssaapi/exclusive_mask_test.go
  common/yak/ssaapi/exclusive_op_test.go
  common/yak/ssaapi/exports_test.go
  common/yak/ssaapi/ssa_exports.go
  common/yak/static_analyzer.go
  common/yak/yak2ssa/builder.go
  common/yak/yak2ssa/ssa_error_test.go
  common/yak/yak2ssa/ssa_vars_test.go
  common/yakgrpc/grpc_language_suggestion.go
  common/yakgrpc/grpc_yaklang_inspect_information.go
Labels: ssa

#829 协议名使用简写 && 修复recovery的bug
  common/bin-parser/parse_test.go
  common/bin-parser/parser/stream_parser/default-parser.go
  common/bin-parser/parser/stream_parser/utils.go
  common/bin-parser/rules/application-layer/http.yaml
  common/bin-parser/rules/ethernet.yaml
  common/bin-parser/rules/internet_protocol_version_6.yaml
  common/bin-parser/rules/user_datagram_protocol.yaml
  common/yakgrpc/grpc_pcapx.go
  common/yakgrpc/grpc_pcapx_test.go
  common/yakgrpc/grpc_pcapx_traffic_ops.go
  common/yakgrpc/yakgrpc.proto
  common/yakgrpc/yakit/traffic.go
  common/yakgrpc/yakit/traffic_storage.go
  common/yakgrpc/ypb/yakgrpc.pb.go
Labels: ready

#844 fix(vm): fix for-range with self modified not work
  common/yak/antlr4yak/executor_test.go
  common/yak/antlr4yak/yakast/for.go
Labels: vm, dangerous

#857 [fix] ssa CanBuildFreeValue
  common/yak/ssa/variable.go
  common/yak/yak2ssa/ssa_error_test.go
Labels: ready, ssa

#861 [Fix]:buildIn method "slice.Insert"
  common/yak/plugin_type_analyzer/ssa_option/yak_options.go
  common/yak/plugin_type_analyzer/test/option_yak_test.go
  common/yak/yak2ssa/builder_object.go
Labels: ready, StaticAnalysis

#868 doc(cli): added
  common/utils/cli/cli.go
Labels: documentation

#859 [Web Fuzzer] Packet Mutate With Methods: Cookie / Header / Get / Post
  common/cybertunnel/tpb/tunnel.pb.go
  common/mutate/http_fuzz.go
  common/mutate/http_pool.go
  common/mutate/method.go
  common/mutate/method_test.go
  common/yak/script_engine_for_fuzz.go
  common/yakgrpc/grpc_fuzzer_mutate_packet_test.go
  common/yakgrpc/yakgrpc.proto
  common/yakgrpc/ypb/yakgrpc.pb.go
  common/yakgrpc/ypb/yakgrpc_grpc.pb.go
Labels: ready

#865 fix(Yak_vm):修改yakvm的异步调用的lastpanic recover逻辑
  common/yak/antlr4yak/yakvm/virtual_machine.go
Labels: ready, dangerous

#875 feat(wsm): add filter type behinder memshell support
  common/wsm/payloads/behinder/static/BasicInfoGo.class
  common/wsm/payloads/behinder/static/CmdGo.class
  common/wsm/payloads/behinder/static/DatabaseGo.class
  common/wsm/payloads/behinder/static/EchoGo.class
  common/wsm/payloads/behinder/static/FileOperationGo.class
Labels: ready

#879 fix(servicescan): web()/service()/all() not required params
  common/yak/yaklib/tools/fingerprint_scan.go
  common/yak/yaktest/mustpass/files/mock_tcp_probe.yak
Labels: ready

#880 [refactor] cli parameter return front-end render type
  common/yak/plugin_type_analyzer/information.go/cli_parameter.go
Labels: need frontend

#881 feat(wsm): clear cache on update and delete operations
  common/yakgrpc/grpc_wsm.go
Labels: ready

#894 doc(synscan/servicescan) add synscan/servicescan && fix yso doc
  common/fp/config.go
  common/utils/pcapfix/fix.go
  common/yak/yaklib/tools/fingerprint_scan.go
  common/yak/yaklib/tools/synscan.go
  common/yso/gadgets.go
  common/yso/utils.go
Labels: ready

#889 refactor(lib-http): use lowhttp to send packet
  common/mutate/http_fuzz.go
  common/utils/lowhttp/http_struct/http_struct.go
  common/utils/lowhttp/modifier.go
  common/utils/lowhttp/poc/poc.go
  common/utils/yakgit/config.go
  common/yak/httptpl/exports.go
  common/yak/yak_to_caller_manager.go
  common/yak/yakdoc/doc/doc.gob.gzip
  common/yak/yaklib/yakhttp/base.go
  common/yak/yaklib/yakit.go
  common/yakgrpc/grpc_fuzzer.go
Labels: Bravo！

#908 fix httpfuzzer
  common/yakgrpc/grpc_fuzzer.go
Labels: ready

#915 add plugin name of error log when mixcaller faild to call yakfunc
  common/yak/yak_to_caller_manager.go
Labels: ready

#933 allow inner tag sync, but parent-child tag is not allowed
  common/fuzztagx/parser/generator.go
  common/fuzztagx/simple_fuzztag_test.go
  common/fuzztagx/sync_test.go
Labels: ready
