Repository yaklang/yaklang, pull requests merged in 2025-03, with the labels that each got.

#2527 fix(mod): fix nil check
  common/yak/ssa/InstructionCover.go
  common/yak/ssa/instructionLazy.go
Labels: intSheep-reviewed

#2530 fix(ssa): fix methodname and add test
  common/yak/go2ssa/builder_ast.go
  common/yak/ssaapi/test/golang/golang_func_test.go
  common/yak/ssaapi/test/java/basic_test.go
  common/yak/ssaapi/test/php/oop_test.go
Labels: ready

#2540 fix(coreplugin):check kind-input is all, because kind will change
  common/coreplugin/base-yak-plugin/SyntaxFlow Searcher.yak
  common/coreplugin/syntaxflow_searcher_test.go
Labels: ready, intSheep-reviewed, Q16G-reviewed

#2515 fix(ssa): fix object side-effect add test
  common/yak/go2ssa/builder_ast.go
  common/yak/go2ssa/builder_literal.go
  common/yak/go2ssa/test/side_effect_test.go
  common/yak/ssa/InstructionEmit.go
  common/yak/ssaapi/test/golang/golang_side_effect_test.go
Labels: ready, intSheep-reviewed, lingze-reviewed

#2533 fix(yakit):yieldYakScript use bizhelper.YieldModel
  common/chaosmaker/rule/model.go
  common/cve/cve_descriptor.go
  common/cve/cveresources/cveType.go
  common/cve/cveresources/cwe.go
  common/syntaxflow/sfdb/rule_op.go
  common/utils/bizhelper/yield.go
  common/yak/ssa/ssadb/audit_node.go
  common/yak/ssa/ssadb/audit_result.go
  common/yak/ssa/ssadb/loader.go
  common/yak/yaklib/tools/fingerprint_scan.go
  common/yakgrpc/yakit/aliveHost.go
  common/yakgrpc/yakit/domain.go
  common/yakgrpc/yakit/extracted_data.go
  common/yakgrpc/yakit/fuzzer_task.go
  common/yakgrpc/yakit/host.go
  common/yakgrpc/yakit/httpflow.go
  common/yakgrpc/yakit/kv.go
  common/yakgrpc/yakit/port.go
  common/yakgrpc/yakit/projects.go
  common/yakgrpc/yakit/recorder.go
  common/yakgrpc/yakit/risk.go
  common/yakgrpc/yakit/websocketflow.go
  common/yakgrpc/yakit/yak_script.go
Labels: need review

#2546 fix(codec-autodecode): base64/base32 detect
  common/yak/yaklib/codec/auto.go
  common/yak/yaklib/codec/codec.go
  common/yak/yaklib/codec/codec_test.go
Labels: ready

#2547 feat(ssaapi):get Instruction count after prog finish
  common/yak/ssa/database_cache_test.go
  common/yak/ssa/database_program.go
  common/yak/ssa/program.go
  common/yak/ssaapi/ssa_compile.go
  common/yak/ssaapi/ssa_compile_fs.go
Labels: need review

#2548 fix(ssaapi):fix filesystem separator for local fs and config info fs
  common/yak/ssaapi/ssa_exports.go
Labels: ready

#2535 fix related bugs in suricata
  common/suricata/config/config.go
  common/suricata/config/number_scope.go
  common/suricata/match/group.go
  common/suricata/match/http.go
  common/yak/cmd/yakcmds/pcap.go
Labels: ready

#2539 feat(open_device): add windows net interface name to guid func
  common/pcapx/pcaputil/capture_test.go
  common/pcapx/pcaputil/open_device.go
  common/pcapx/pcaputil/open_device_darwin.go
  common/pcapx/pcaputil/open_device_linux.go
  common/pcapx/pcaputil/open_device_windows..go
Labels: ready, v1ll4n-reviewed

#2556 refactor(dialx):add refuse retry
  common/netstackvm/listen.go
  common/netstackvm/netvm.go
  common/netstackvm/netvm_test.go
  common/netstackvm/tun_mitm_test.go
  common/netx/dialx.go
  common/netx/mustpass/raw_net_dns_test.go
  common/netx/mustpass/timeout_test.go
  common/netx/systemproxy_test.go
Labels: ready, v1ll4n-reviewed

#2553 fix(lib-json): loads as omap, fix test
  common/yak/yaklib/json.go
  common/yak/yaklib/json_test.go
Labels: v1ll4n-reviewed

#2564 feat(ssadb):save and load irCode have Cache
  common/yak/ssa/database_cache.go
  common/yak/ssa/ssadb/code.go
Labels: need review

#2561 fix(payload):unexpected trim left space
  common/schema/payload.go
  common/yakgrpc/grpc_managePayload_test.go
  common/yakgrpc/yakit/payload.go
Labels: ready, v1ll4n-reviewed

#2568 change default withIndent in json
  common/yak/yaklib/json.go
  common/yak/yaktest/mustpass/files/json-dumps.yak
Labels: ready

#2529 refactor(ssaapi):refactor cross process analysis to support DFS
  common/yak/ssaapi/analyze_context.go
  common/yak/ssaapi/analyze_cross_process.go
  common/yak/ssaapi/analyze_cross_process_test.go
  common/yak/ssaapi/exclusive_z_bottom_use.go
  common/yak/ssaapi/exclusive_z_top_defs.go
Labels: need review

#2570 fix(mcp): 使用 EnumString 替换 Enum
  common/mcp/brute.go
  common/mcp/codec.go
  common/mcp/mcp-go/mcp/tools.go
  common/mcp/reverse_shell.go
Labels: ready

#2563 fix(sf): use ai to describe desc information
  common/consts/hash.go
  common/consts/hash.go.bak
  common/syntaxflow/sfbuildin/buildin/golang/cwe-1336-ssti/golang-template-ssti.sf
  common/syntaxflow/sfbuildin/buildin/golang/cwe-200-information-exposure/golang-ftp-information-exposure.sf
  common/syntaxflow/sfbuildin/buildin/golang/cwe-200-information-exposure/golang-sql-information-exposure.sf
  common/syntaxflow/sfbuildin/buildin/golang/cwe-259-hard-coded-password/golang-ftp-hard-coded-password.sf
  common/syntaxflow/sfbuildin/buildin/golang/cwe-259-hard-coded-password/golang-ldap-hard-coded-password.sf
  common/syntaxflow/sfbuildin/buildin/golang/cwe-287-improper-authentication/golang-nil-password.sf
  common/syntaxflow/sfbuildin/buildin/golang/cwe-434-file-upload/golang-file-upload.sf
  common/syntaxflow/sfbuildin/buildin/golang/cwe-601-open-redirect/golang-open-redirect.sf
  common/syntaxflow/sfbuildin/buildin/golang/cwe-611-xxe/golang-xxe-read-any-file.sf
  common/syntaxflow/sfbuildin/buildin/golang/cwe-73-unfiltered-file-or-path/golang-unfiltered-file-or-path.sf
  common/syntaxflow/sfbuildin/buildin/golang/cwe-77-command-injection/golang-command-injection.sf
  common/syntaxflow/sfbuildin/buildin/golang/cwe-79-xss/golang-reflected-xss-template.sf
  common/syntaxflow/sfbuildin/buildin/golang/cwe-79-xss/golang-reflected-xss-write.sf
  common/syntaxflow/sfbuildin/buildin/golang/cwe-863-incorrect-authorization/golang-filepath-missing-permission-check.sf
  common/syntaxflow/sfbuildin/buildin/golang/cwe-89-sql-injection/golang-database-gin-sql.sf
  common/syntaxflow/sfbuildin/buildin/golang/cwe-89-sql-injection/golang-database-net-sql.sf
  common/syntaxflow/sfbuildin/buildin/golang/cwe-89-sql-injection/golang-ent-sql.sf
  common/syntaxflow/sfbuildin/buildin/golang/cwe-89-sql-injection/golang-gorm-sql.sf
  common/syntaxflow/sfbuildin/buildin/golang/cwe-89-sql-injection/golang-pop-sql.sf
  common/syntaxflow/sfbuildin/buildin/golang/cwe-89-sql-injection/golang-reform-sql.sf
  common/syntaxflow/sfbuildin/buildin/golang/cwe-89-sql-injection/golang-sqlx-sql.sf
  common/syntaxflow/sfbuildin/buildin/golang/cwe-90-ldap-injection/golang-ldap-injection.sf
  common/syntaxflow/sfbuildin/buildin/golang/cwe-918-ssrf/golang-http-ssrf.sf
  common/syntaxflow/sfbuildin/buildin/golang/lib/golang-file-path.sf
  common/syntaxflow/sfbuildin/buildin/golang/lib/golang-fmt-print.sf
  common/syntaxflow/sfbuildin/buildin/golang/lib/golang-template.sf
  common/syntaxflow/sfbuildin/buildin/java/cwe-252-unchecked-return-value/java-zip-unchecked-return-value.sf
Labels: ready

#2550 refactor: update HTML files to use local static resources instead of …
  common/coreplugin/fastjson_test.go
  common/coreplugin/utils.go
  common/coreplugin/utils_test.go
  common/vulinbox/html/mall/vul_mall_login.html
  common/vulinbox/html/mall/vul_mall_register.html
  common/vulinbox/html/vul_cryoto_sm_sm4.html
  common/vulinbox/html/vul_cryptojs_basic.html
  common/vulinbox/html/vul_cryptojs_rsa.html
  common/vulinbox/html/vul_cryptojs_rsa_and_aes.html
  common/vulinbox/html/vul_cryptojs_rsa_keyfromserver.html
  common/vulinbox/html/vul_cryptojs_rsa_keyfromserver_withresponse.html
  common/vulinbox/html/vul_cryptojs_template.html
  common/vulinbox/html/vul_csrf_safe.html
  common/vulinbox/html/vul_csrf_unsafe.html
  common/vulinbox/html/vul_fastjson.html
  common/vulinbox/html/vul_login_jwt_login.html
  common/vulinbox/html/vul_user_login.html
  common/vulinbox/html/vul_user_profile.html
  common/vulinbox/html/vul_user_register.html
  common/vulinbox/vul_fastjson.go
  common/yakgrpc/util.go
Labels: ready

#2541 response chunk hacked for mitm interactive hijack
  common/crep/mitm.go
  common/crep/mitm_config.go
  common/minimartian/lowhttp_exec.go
  common/minimartian/proxy.go
  common/schema/httpflow.go
  common/utils/bytes_reader.go
  common/utils/bytes_reader_test.go
  common/utils/http_response_builder.go
  common/utils/lowhttp/httpctx/base.go
  common/vulinbox/vul_misc.go
  common/yakgrpc/grpc_httpflow.go
  common/yakgrpc/grpc_mitm.go
  common/yakgrpc/grpc_mitm_test.go
  common/yakgrpc/model/httpflow.go
  common/yakgrpc/yakgrpc.proto
  common/yakgrpc/yakit/httpflow.go
  common/yakgrpc/ypb/yakgrpc.pb.go
  common/yakgrpc/ypb/yakgrpc_grpc.pb.go
Labels: v1ll4n-reviewed

#2577 add word parser
  common/utils/fileparser/parser.go
  common/utils/fileparser/parser_test.go
  common/utils/fileparser/wordparser/classifier.go
  common/utils/fileparser/wordparser/dumper.go
  common/utils/fileparser/wordparser/word.go
  common/utils/fileparser/wordparser/word_test.go
Labels: ready

#2582 fix(ssadb):delete result with node and edge
  common/utils/bizhelper/dbutil.go
  common/yak/ssa/ssadb/audit_node.go
  common/yak/ssa/ssadb/audit_result.go
  common/yak/ssa/ssadb/audit_result_test.go
  common/yakgrpc/grpc_syntaxflow_result.go
  common/yakgrpc/grpc_syntaxflow_scan_task_test.go
Labels: ready

#2592 fix(binx): enhance PartDescriptor handling and add FindResultByIdenti…
  common/binx/config.go
  common/binx/exports.go
  common/binx/format.go
  common/binx/format_test.go
  common/binx/result.go
  common/yak/yaktest/mustpass/files/binx.yak
Labels: ready

#2596 feat(taskstack): use mcp tool, fix tests
  common/ai/taskstack/mocktools.go
  common/ai/taskstack/mocktools_test.go
  common/ai/taskstack/task_invoke_test.go
  common/ai/taskstack/task_test.go
  common/ai/taskstack/taskstack_test.go
  common/ai/taskstack/tool.go
  common/ai/taskstack/tool_example.go
  common/ai/taskstack/tool_invoke_result.go
  common/ai/taskstack/tool_invoke_test.go
  common/ai/taskstack/tool_option_test.go
  common/ai/taskstack/tool_result_test.go
  common/ai/taskstack/tool_test.go
  common/mcp/mcp-go/mcp/tools.go
  go.mod
  go.sum
  go.work.sum
Labels: ready

#2590 feat(lib-json): load as other type(array, num...)
  common/yak/yaklib/json.go
  common/yak/yaklib/json_test.go
  common/yak/yaktest/mustpass/files/json.yak
Labels: ready

#2607 Adds Java decompiler yakurl action support
  common/yak/yakurl/iface.go
  common/yak/yakurl/java_decompiler_action.go
  common/yak/yakurl/java_decompiler_action_test.go
Labels: ready, v1ll4n-reviewed, intSheep-reviewed

#2618 fix(yakit):fix QueryScreenRecorder panic
  common/yakgrpc/yakit/recorder.go
Labels: ready

#2620 Update README.md
  README.md
Labels: ready

#2589 Feat/Grpc/AnalyzeHTTPFlow
  common/schema/database_schema.go
  common/schema/extracted_data.go
  common/schema/httpflow_analyze.go
  common/yak/hook_mixed_plugin_caller.go
  common/yak/static_analyzer/score_rules/plugin_score_rules.go
  common/yak/static_analyzer/ssa_option/plugin_options.go
  common/yak/static_analyzer/test/rules_plugin_function_test.go
  common/yakgrpc/grpc_httpflow_analyze.go
  common/yakgrpc/grpc_httpflow_analyze_test.go
  common/yakgrpc/grpc_mitm_extract_data.go
  common/yakgrpc/grpc_mitm_extrat_data_test.go
  common/yakgrpc/grpc_mitm_replacers.go
  common/yakgrpc/yakgrpc.proto
  common/yakgrpc/yakit/extracted_data.go
  common/yakgrpc/yakit/httpflow.go
  common/yakgrpc/yakit/httpflow_analyze.go
  common/yakgrpc/ypb/yakgrpc.pb.go
  common/yakgrpc/ypb/yakgrpc_grpc.pb.go
Labels: ready
