Repository yaklang/yaklang, pull requests merged in 2025-07, with the labels that each got.

#2942 Add vector data manager
  .github/workflows/essential-tests.yml
  common/ai/embedding/base.go
  common/ai/rag/exports.go
  common/ai/rag/memory_store.go
  common/ai/rag/plugins_rag/cmd/main.go
  common/ai/rag/plugins_rag/export_import_test.go
  common/ai/rag/plugins_rag/exports.go
  common/ai/rag/plugins_rag/plugin_indexer.go
  common/ai/rag/plugins_rag/plugins_rag_manager.go
  common/ai/rag/rag.go
  common/ai/rag/rag_test.go
  common/ai/rag/sqlitedb_store.go
  common/ai/rag/sqlitedb_store_test.go
  common/ai/rag/sqlitedb_store_utils.go
  common/utils/bizhelper/dbutil.go
  common/utils/bizhelper/dbutils_test.go
  common/utils/bizhelper/export.go
  common/utils/bizhelper/export_test.go
  common/utils/bizhelper/import.go
  common/utils/bizhelper/utils.go
  common/utils/bizhelper/yield.go
  common/utils/utils.go
  common/yakgrpc/grpc_local_model.go
  common/yakgrpc/yakgrpc.proto
  common/yakgrpc/yakit/yak_script.go
  common/yakgrpc/ypb/yakgrpc.pb.go
  common/yakgrpc/ypb/yakgrpc_grpc.pb.go
Labels: ready

#2950 fix(ssaapi):delete extra dataflow analysis log
  common/yak/ssaapi/exclusive_z_bottom_use.go
  common/yak/ssaapi/exclusive_z_top_defs.go
Labels: ready

#2965 fix(sf):determine whether the mybatis file is using more lenient cond…
  common/yak/ssaapi/sf_native_call_xml.go
  common/yak/ssaapi/test/java/native_call_mybatis_weak_param_test.go
Labels: ready

#2911 add SyntaxFlowRule evaluation functionality provide GRPC and CLI interface for use
  .github/workflows/essential-tests.yml
  common/consts/hash.go
  common/consts/hash.go.bak
  common/schema/plugin_rule.go
  common/syntaxflow/sfanalyzer/score.go
  common/syntaxflow/sfanalyzer/sf_analyzer.go
  common/syntaxflow/sfanalyzer/sf_analyzer_test.go
  common/syntaxflow/sfanalyzer/testdata/demoRule.sf
  common/syntaxflow/sfbuildin/buildin/buildin-rule-test/scan_test.go
  common/syntaxflow/sfbuildin/buildin/java/cwe-200-exposure-of-sensitive-information/java-spring-resource-handler-location.sf
  common/syntaxflow/sfbuildin/buildin/java/cwe-352-csrf/java-springframework-config-disable-csrf.sf
  common/syntaxflow/sfbuildin/buildin/java/cwe-611-xxe/java-saxbuilder-unsafe.sf
  common/syntaxflow/sfbuildin/buildin/java/cwe-611-xxe/java-saxparser-factory-unsafe.sf
  common/syntaxflow/sfbuildin/buildin/java/cwe-611-xxe/java-saxreader-unsafe.sf
  common/syntaxflow/sfbuildin/buildin/java/cwe-749-exposed-dangerous-method-or-function/java-access-specifier-manipulation.sf
  common/syntaxflow/sfdb/rule_versions.json
  common/syntaxflow/sfvm/frame.go
  common/syntaxflow/sfvm/visit_statement.go
  common/syntaxflow/sfvm/visitor.go
  common/yak/cmd/yakcmds/ssacli.go
  common/yak/cmd/yakcmds/ssacli_test.go
  common/yak/java/java2ssa/java_full_type_name.go
  common/yak/java/tests/type_test.go
  common/yak/ssaapi/test/java/native_call_typeName_test.go
  common/yak/ssaapi/test/ssatest/utils4analysis.go
  common/yakgrpc/grpc_smoking_evaluate_plugin.go
  common/yakgrpc/grpc_smoking_evaluate_plugin_batch.go
  common/yakgrpc/grpc_smoking_evaluate_sf_rule_test.go
  common/yakgrpc/yakgrpc.proto
  common/yakgrpc/yakit/yak_script.go
  common/yakgrpc/ypb/yakgrpc.pb.go
Labels: need to rebase

#2974 fix(ssa): OrType should get method
  common/yak/ssa/next.go
  common/yak/ssa/type.go
  common/yak/ssa/type_test.go
  common/yak/static_analyzer/ssa_option/yak_options.go
  common/yak/yak2ssa/test/error_test.go
Labels: ready

#2972 fix(sf): add new golang sfbuild
  common/consts/hash.go
  common/consts/hash.go.bak
  common/syntaxflow/sfbuildin/buildin/golang/cwe-200-information-exposure/golang-sql-information-exposure.sf
  common/syntaxflow/sfbuildin/buildin/golang/cwe-259-hard-coded-password/golang-ldap-hard-coded-password.sf
  common/syntaxflow/sfbuildin/buildin/golang/cwe-601-open-redirect/golang-gin-context-redirect.sf
  common/syntaxflow/sfbuildin/buildin/golang/cwe-601-open-redirect/golang-http-open-redirect.sf
  common/syntaxflow/sfbuildin/buildin/golang/cwe-73-unfiltered-file-or-path/golang-unfiltered-file-or-path.sf
  common/syntaxflow/sfbuildin/buildin/golang/cwe-79-xss/golang-reflected-xss-beego.sf
  common/syntaxflow/sfbuildin/buildin/golang/cwe-79-xss/golang-reflected-xss-template.sf
  common/syntaxflow/sfbuildin/buildin/golang/cwe-79-xss/golang-reflected-xss-write.sf
  common/syntaxflow/sfbuildin/buildin/golang/cwe-863-incorrect-authorization/golang-filepath-missing-permission-check.sf
  common/syntaxflow/sfbuildin/buildin/golang/cwe-89-sql-injection/golang-database-gin-sql.sf
  common/syntaxflow/sfbuildin/buildin/golang/cwe-89-sql-injection/golang-ent-sql.sf
  common/syntaxflow/sfbuildin/buildin/golang/cwe-89-sql-injection/golang-service-sql.sf
  common/syntaxflow/sfbuildin/buildin/golang/cwe-942-cors/golang-gin-context-cors.sf
  common/syntaxflow/sfbuildin/buildin/golang/lib/golang-ldap-sink.sf
  common/syntaxflow/sfbuildin/buildin/golang/lib/http/golang-http-handlefunc-net.sf
  common/syntaxflow/sfbuildin/buildin/golang/lib/read/golang-file-read-bufio.sf
  common/syntaxflow/sfbuildin/buildin/golang/lib/read/golang-file-read-ioutil.sf
  common/syntaxflow/sfbuildin/buildin/golang/lib/read/golang-file-read-os.sf
  common/syntaxflow/sfbuildin/buildin/golang/lib/read/golang-file-read-path-bufio.sf
  common/syntaxflow/sfbuildin/buildin/golang/lib/read/golang-file-read-path-ioutil.sf
  common/syntaxflow/sfbuildin/buildin/golang/lib/read/golang-file-read-path-os.sf
  common/syntaxflow/sfbuildin/buildin/golang/lib/read/golang-file-read-path-sink.sf
  common/syntaxflow/sfbuildin/buildin/golang/lib/read/golang-file-read-sink.sf
  common/syntaxflow/sfbuildin/buildin/golang/lib/sqldb/golang-database-from-param.sf
  common/syntaxflow/sfbuildin/buildin/golang/lib/sqldb/golang-database-pop.sf
  common/syntaxflow/sfbuildin/buildin/golang/lib/sqldb/golang-database-sink.sf
  common/syntaxflow/sfbuildin/buildin/golang/lib/write/golang-file-write-bufio.sf
  common/syntaxflow/sfbuildin/buildin/golang/lib/write/golang-file-write-ioutil.sf
  common/syntaxflow/sfbuildin/buildin/golang/lib/write/golang-file-write-os.sf
  common/syntaxflow/sfbuildin/buildin/golang/lib/write/golang-file-write-path-bufio.sf
  common/syntaxflow/sfbuildin/buildin/golang/lib/write/golang-file-write-path-ioutil.sf
  common/syntaxflow/sfbuildin/buildin/golang/lib/write/golang-file-write-path-os.sf
  common/syntaxflow/sfbuildin/buildin/golang/lib/write/golang-file-write-path-sink.sf
  common/syntaxflow/sfbuildin/buildin/golang/lib/write/golang-file-write-sink.sf
  common/syntaxflow/sfdb/rule_versions.json
  common/yak/go2ssa/builder_ast.go
  common/yak/ssa/member_call.go
  common/yak/ssaapi/test/golang/golang_obj_test.go
  common/yak/yakurl/ssaurl_test.go
Labels: ready

#2982 fix(plugin): fix exclude
  common/consts/hash.go
  common/consts/hash.go.bak
  common/coreplugin/base-yak-plugin/SSA 项目探测.yak
  common/yak/ssaapi/test/php/exclude_test.go
Labels: ready

#2980 fix(grpc): add codec save and update api
  common/schema/codec_flow.go
  common/yakgrpc/grpc_codec.go
  common/yakgrpc/grpc_codec_test.go
  common/yakgrpc/yakgrpc.proto
  common/yakgrpc/yakit/codecflow.go
  common/yakgrpc/ypb/yakgrpc.pb.go
Labels: 🔜：need frontend

#2996 feat(fingerprint):use older state when http request failed
  .github/workflows/essential-tests.yml
  common/fp/fingerprint_test.go
  common/fp/fingerprint_webdetector.go
Labels: ready

#3004 Feature/ssa/c/antlr
  common/consts/ssa.go
  common/yak/antlr4c/CLexer.g4
  common/yak/antlr4c/CParser.g4
  common/yak/antlr4c/antlr4-schema.bat
  common/yak/antlr4c/antlr4-schema.sh
  common/yak/antlr4c/parser/CLexer.interp
  common/yak/antlr4c/parser/CLexer.tokens
  common/yak/antlr4c/parser/CParser.interp
  common/yak/antlr4c/parser/CParser.tokens
  common/yak/antlr4c/parser/c_lexer.go
  common/yak/antlr4c/parser/c_parser.go
  common/yak/antlr4c/parser/cparser_base_visitor.go
  common/yak/antlr4c/parser/cparser_visitor.go
  common/yak/antlr4c/syntax_test.go
  common/yak/antlr4c/test/BinaryDigit.c
  common/yak/antlr4c/test/FuncCallAsFuncArgument.c
  common/yak/antlr4c/test/FuncCallwithVarArgs.c
  common/yak/antlr4c/test/FuncForwardDeclaration.c
  common/yak/antlr4c/test/FunctionCall.c
  common/yak/antlr4c/test/FunctionPointer.c
  common/yak/antlr4c/test/FunctionReturningPointer.c
  common/yak/antlr4c/test/ParameterOfPointerType.c
  common/yak/antlr4c/test/TypeCast.c
  common/yak/antlr4c/test/Wmisleading-indentation.pp.c
  common/yak/antlr4c/test/add.c
  common/yak/antlr4c/test/bt.c
  common/yak/antlr4c/test/dialog.c
  common/yak/antlr4c/test/helloworld.c
  common/yak/antlr4c/test/integrate.c
  common/yak/antlr4c/test/label_before_closing_curly_brace.c
  common/yak/antlr4c/test/ll.c
  common/yak/antlr4c/test/pr403.c
  common/yak/antlr4go/GoLexer.g4
  common/yak/antlr4go/GoParser.g4
  common/yak/antlr4go/antlr4-schema.bat
  common/yak/antlr4go/antlr4-schema.sh
  common/yak/antlr4go/syntax_test.go
  common/yak/c2ssa/builder.go
  common/yak/c2ssa/builder_ast.go
  common/yak/c2ssa/builder_express.go
  common/yak/c2ssa/error_message.go
  common/yak/c2ssa/test/baisic_test.go
  common/yak/c2ssa/test/utils_test.go
Labels: ready

#3006 fix(yakgrpc): add grpc diff test
  common/yakgrpc/grpc_syntaxflow_scan_test.go
  common/yakgrpc/yakit/ssa_risk.go
Labels: ready

#3015 fix(grpc):fix JSON schema too long to render
  common/yak/ssa/InstructionEmit.go
  common/yakgrpc/grpc_yaklang_inspect_information_test.go
Labels: ready
