Repository yaklang/yaklang, pull requests merged in 2025-05, with the labels that each got.

#2746 fix(lowhttp): temporary improve lowhttp
  common/utils/lowhttp/conn_pool.go
  common/utils/lowhttp/http2_serve.go
  common/utils/lowhttp/http2_server_config.go
Labels: ready

#2778 feat: add capture started callback to pcaputil and fix route
  common/pcapx/pcaputil/config.go
  common/synscanx/arp.go
  common/synscanx/handle.go
  common/synscanx/scanx.go
  common/utils/netutil/route.go
  common/yak/yaklib/tools/synscanx_test.go
Labels: v1ll4n-reviewed

#2784 feat(cli):xpath support output file
  common/yak/cmd/yakcmds/utils.go
Labels: ready

#2756 feat(sf):support export and import rule by rule id.
  common/syntaxflow/sfdb/rule_and_group_op_test.go
  common/syntaxflow/sfdb/rule_group_op.go
  common/syntaxflow/sfdb/rule_op.go
  common/utils/bizhelper/export.go
  common/yakgrpc/grpc_syntaxflow_export.go
  common/yakgrpc/grpc_syntaxflow_export_test.go
Labels: ready

#2794 Fix type casting bug in Yak engine; support recognizing underlying ty…
  common/yak/antlr4yak/buildin_operators.go
  common/yak/antlr4yak/executor_test.go
  common/yak/antlr4yak/yakvm/utils.go
  common/yak/antlr4yak/yakvm/value.go
  common/yak/antlr4yak/yakvm/vm_exec.go
Labels: ready, v1ll4n-reviewed

#2795 fix(grpc):program return total risk number
  common/yakgrpc/yakgrpc.proto
  common/yakgrpc/yakit/ssa_program.go
  common/yakgrpc/ypb/yakgrpc.pb.go
Labels: need review

#2813 add more public/private key format support
  common/utils/tlsutils/crypto.go
  common/utils/tlsutils/crypto_test.go
  common/vulinbox/vul_cryptojs_base.go
  common/yak/yaklib/codec.go
  common/yak/yaklib/codec/codegrpc/codec_grpc_methods.go
  common/yak/yaklib/tls.go
Labels: ready

#2817 fix(mitm-grpc):fix mitm rpc invalid utf8 message
  common/yak/yaklib/codec/gbk.go
  common/yakgrpc/grpc_mitm.go
  common/yakgrpc/grpc_mitm_v2.go
  common/yakgrpc/message_utf8.go
Labels: ready

#2831 Add mcp server grpc interface
  common/mcp/payload.go
  common/mcp/server.go
  common/mcp/server_config_resource.go
  common/mcp/server_config_tool.go
  common/yak/cmd/yak.go
  common/yak/depinjector/depinjector.go
  common/yakgrpc/grpc_extract_data.go
  common/yakgrpc/grpc_mcp.go
  common/yakgrpc/grpc_mcp_test.go
  common/yakgrpc/yakgrpc.proto
  common/yakgrpc/ypb/yakgrpc.pb.go
  common/yakgrpc/ypb/yakgrpc_grpc.pb.go
Labels: ready
