Repository yaklang/yaklang, pull requests merged in 2025-04, with the labels that each got.

#2636 fix(grpc):listing model keys is not mandatory
  common/yakgrpc/grpc_ai.go
Labels: ready

#2642 fix sf group show rule count error
  common/schema/syntaxflow_rule_group.go
Labels: ready

#2645 feat(cmd):add magic boundary
  common/yak/cmd/yakcmds/utils.go
Labels: ready

#2652 fix(sf):add severity alias
  common/schema/syntaxflow_rule.go
Labels: ready, v1ll4n-reviewed

#2651 fix(httpflow):fix keyword query have not quote
  common/yakgrpc/grpc_httpflow_test.go
  common/yakgrpc/yakit/httpflow.go
Labels: ready

#2639 feat(coreplugin):add path and header sql injection core plugin
  common/coreplugin/base-yak-plugin/SQL注入-Path参数注入.yak
  common/coreplugin/base-yak-plugin/SQL注入-高危Header注入.yak
  common/coreplugin/coreplugin.go
  common/vulinbox/database_schema.go
  common/vulinbox/db.go
  common/vulinbox/html/visitor_source.html
  common/vulinbox/model_visitor.go
  common/vulinbox/vul_sqli.go
Labels: ready

#2663 fix(dialx):fix dial proxy retry endless loop
  common/netx/dialx.go
Labels: ready

#2672 fix(ssa):fixup sf result load bug
  common/yak/ssa/ssadb/audit_node.go
  common/yak/ssaapi/sf_result.go
  common/yak/ssaapi/sf_result_database_test.go
  common/yak/ssaapi/sf_result_value.go
  common/yak/yakurl/ssaurl_test.go
Labels: need review

#2675 feature(ctx): feature download ctx
  common/utils/utils.go
  common/yakgrpc/grpc_cve.go
Labels: v1ll4n-reviewed

#2670 fix(ssarisk):escape some field before build ssa risk
  common/yak/ssaapi/sf_result_risk.go
Labels: ready

#2683 fix java class parser
  common/javaclassparser/marshal.go
  common/javaclassparser/utils.go
Labels: ready

#2654 migrate version print func to avoid unnecessary db init
  common/utils/os_utils.go
  common/yak/cmd/yak.go
Labels: 危

#2690 fix(grpc):fix analyze http flow concurrency send msg
  common/yakgrpc/grpc_httpflow_analyze.go
  common/yakgrpc/grpc_httpflow_analyze_test.go
Labels: ready

#2707 fix(ssacli):fix report format desc
  common/yak/cmd/yakcmds/ssacli.go
Labels: ready

#2700 fix the file path separator bug of zipfs on windows
  common/utils/filesys/zip_fs.go
  common/yak/yakurl/java_decompiler/file_path_test.go
Labels: ready

#2713 Add 'flow control' option to Fuzztagx; skip flow control tags during …
  common/fuzztagx/fuzztag.go
  common/fuzztagx/parser/generator.go
  common/fuzztagx/parser/tag.go
  common/fuzztagx/reader_test.go
  common/mutate/fuzztag.go
  common/mutate/fuzztag_test.go
Labels: ready

#2717 fix(grpc):fix SetTagForHTTPFlow error
  common/yakgrpc/grpc_httpflow.go
  common/yakgrpc/yakit/httpflow.go
Labels: ready

#2718 feat(httpflow):add request_length and payload filter
  common/mcp/httpflow.go
  common/schema/httpflow.go
  common/yakgrpc/grpc_httpflow.go
  common/yakgrpc/model/httpflow.go
  common/yakgrpc/yakgrpc.proto
  common/yakgrpc/yakit/httpflow.go
  common/yakgrpc/ypb/yakgrpc.pb.go
Labels: ready

#2694 fix(mitmv2):fix mitmv2 condition hijack feedback
  common/yakgrpc/grpc_mitm_v2.go
Labels: need review

#2729 feat(plugin):enhance time delay sql injection plugin by extend testin…
  common/coreplugin/base-yak-plugin/SQL注入-时间盲注-Sleep.yak
Labels: ready

#2731 fix(grpc):fix httpflow analyze websocket update tag
  common/yakgrpc/yakit/httpflow_analyze.go
  common/yakgrpc/yakit/websocketflow.go
Labels: ready

#2733 fix(java2ssa):fix the value type name which only be declared.
  common/yak/java/java2ssa/java_full_type_name.go
  common/yak/java/java2ssa/visit_package_n_class.go
  common/yak/java/java2ssa/visit_stmt_block_expr.go
  common/yak/ssaapi/test/java/native_call_typeName_test.go
Labels: ready
