Repository yaklang/yaklang, pull requests merged in 2025-06, with the labels that each got.

#2825 Feature/ssa/mysql
  common/consts/database.go
  common/consts/ssa.go
  common/consts/yakit.go
  common/consts/yakit_home_unix.go
  common/schema/project.go
  common/utils/database_cache.go
  common/yak/cmd/yakcmds/ssacli.go
  common/yak/ssa/ssadb/audit_node.go
  common/yak/ssa/ssadb/audit_result.go
  common/yak/ssa/ssadb/code.go
  common/yak/ssa/ssadb/source.go
  common/yak/ssa/ssadb/source_filesys.go
  common/yak/ssaapi/sf_result_database_test.go
  common/yak/ssaapi/ssa_compile.go
  common/yak/ssaapi/ssa_compile_project.go
  common/yak/ssaapi/ssa_exports.go
  common/yakgrpc/grpc_project.go
  common/yakgrpc/yakgrpc.proto
  common/yakgrpc/yakit/projects.go
  common/yakgrpc/yakit/ssa_program.go
  common/yakgrpc/ypb/yakgrpc.pb.go
Labels: ready

#2822 Add authorization bypass testing target
  common/vulinbox/html/vul_auth_bypass_dashboard.html
  common/vulinbox/html/vul_auth_bypass_login.html
  common/vulinbox/route.go
  common/vulinbox/vul_authorization_bypass.go
Labels: ready

#2853 improve SM2 decryption compatibility
  common/yak/cmd/yak.go
  common/yak/yaklib/codec/sm2.go
  common/yak/yaklib/codec/sm2_test.go
Labels: v1ll4n-reviewed

#2864 feat(ssaapi):save value support context
  common/syntaxflow/sfvm/config.go
  common/utils/graph/dfs_graph_builder.go
  common/utils/graph/graph_builder_test.go
  common/yak/ssaapi/sf_query.go
  common/yak/ssaapi/sf_result_save.go
  common/yak/ssaapi/values_db.go
  common/yak/ssaapi/values_graph_dot.go
Labels: need review

#2846 add support for break with label name
  common/yak/ssa/cfg.go
  common/yak/ssa/label.go
  common/yak/ssa/ssautil/cfg.go
  common/yak/ssa/value.go
  common/yak/typescript/js2ssa/auxiliary.go
  common/yak/typescript/js2ssa/build_from_ast.go
  common/yak/typescript/js2ssa/builder.go
  common/yak/typescript/js2ssa/builder_prehandler.go
  common/yak/typescript/js2ssa/tests/ast2ssa_test.go
  common/yak/typescript/js2ssa/tests/builder_large_test.go
  common/yak/typescript/js2ssa/tests/cfg_test.go
  common/yak/typescript/js2ssa/tests/utils_test.go
Labels: need review

#2844 Feat/portscan/support scan with fg group
  common/fp/config.go
  common/fp/fingerprint/parsers/exp_parser.go
  common/yak/yaklib/tools/fingerprint_scan.go
  common/yakgrpc/grpc_fingerprint_test.go
  common/yakgrpc/grpc_fingerprint_transfer.go
  common/yakgrpc/grpc_fingerprint_transfer_test.go
  common/yakgrpc/grpc_scanPort.go
  common/yakgrpc/grpc_scanPort_script.yak
  common/yakgrpc/grpc_scanPort_test.go
  common/yakgrpc/yakgrpc.proto
  common/yakgrpc/yakit/fingerprint_general_rule.go
  common/yakgrpc/ypb/yakgrpc.pb.go
Labels: need review

#2877 fix: add support for JSON array extraction and related tests
  common/jsonextractor/extract_test.go
  common/jsonextractor/extractor.go
  common/yak/yaklib/strings.go
Labels: ready

#2906 fix(yaklib):fix ord error for rune
  common/yak/yaklib/global.go
  common/yak/yaklib/global_test.go
Labels: ready

#2910 refactor(netstack-vm):add some option for filter
  common/netstackvm/netvm_entry.go
  common/netstackvm/tun_mitm_test.go
  common/netstackvm/utils_client.go
Labels: ready

#2915 fix(lowhttp):fix content length is negative number will panic
  common/utils/lowhttp/exec.go
  common/utils/lowhttp/exec_test.go
Labels: ready

#2919 fix(utils):re starting with `(?`, but not any pattern, the rule will …
  common/utils/regexp2.go
  common/yakgrpc/grpc_mitm_replacers_test.go
Labels: ready
